### ISSUE TITLE
Ansible Galaxy

### ISSUE THREAD

**Issue by spech66** [eumel8/ansible-otc#18]
Hi,
thank you for the awesome work. Is there any chance that you provide the otc roles as Galaxy modules?
Best regards
Sebastian

**Comment by eumel8** [comment]
good idea! needs some preparation

**Comment by spech66** [comment]
Awesome! We are really looking forward to this 👍  btw. is it possible that the ecs create template is missing the ecs_ram and ecs_vcpus values?

**Comment by eumel8** [comment]
Okay, there is now a new branch "galaxy" within the documentation https://ansible-otc.readthedocs.io/en/galaxy/
It's more or less copied code and needs to be tested.
Regarding ecs_ram ecs_vcpu in ecs create template: that depends on the flavor and will be ordered here:
https://github.com/eumel8/otc_ecs/blob/master/tasks/lookup.yml#L44

**Comment by eumel8** [comment]
#20
